// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PuzKit3D.SharedKernel.Infrastructure.Identity;

#nullable disable

namespace PuzKit3D.SharedKernel.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("identity_role_claim", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("identity_user_claim", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("identity_user_login", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("identity_user_token", "identity");
                });

            modelBuilder.Entity("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("identity_role", "identity");

                    b.HasData(
                        new
                        {
                            Id = "9b7da615-9c41-4700-92a9-ca17337c5724",
                            CreatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full system access",
                            Name = "System Administrator",
                            NormalizedName = "SYSTEM_ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "0b42c919-01c0-4109-ba04-d848c45dc413",
                            CreatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Low-level business access",
                            Name = "Business Manager",
                            NormalizedName = "BUSINESS_MANAGER"
                        },
                        new
                        {
                            Id = "1a0d505f-46d8-4aaf-92c7-71ba90443dcb",
                            CreatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-level business access",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = "f634ede8-7091-48da-a969-2bf90ef86f2c",
                            CreatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Standard customer access",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationRolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.Property<string>("Permission")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoleId", "Permission");

                    b.ToTable("identity_user_role_permission", "identity");

                    b.HasData(
                        new
                        {
                            RoleId = "9b7da615-9c41-4700-92a9-ca17337c5724",
                            Permission = "users:view",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7799)
                        },
                        new
                        {
                            RoleId = "9b7da615-9c41-4700-92a9-ca17337c5724",
                            Permission = "users:create",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7805)
                        },
                        new
                        {
                            RoleId = "9b7da615-9c41-4700-92a9-ca17337c5724",
                            Permission = "users:update",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7805)
                        },
                        new
                        {
                            RoleId = "9b7da615-9c41-4700-92a9-ca17337c5724",
                            Permission = "users:delete",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7806)
                        },
                        new
                        {
                            RoleId = "9b7da615-9c41-4700-92a9-ca17337c5724",
                            Permission = "users:roles:manage",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7807)
                        },
                        new
                        {
                            RoleId = "9b7da615-9c41-4700-92a9-ca17337c5724",
                            Permission = "users:permissions:manage",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7807)
                        },
                        new
                        {
                            RoleId = "0b42c919-01c0-4109-ba04-d848c45dc413",
                            Permission = "catalog:assembly-methods:view",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7837)
                        },
                        new
                        {
                            RoleId = "0b42c919-01c0-4109-ba04-d848c45dc413",
                            Permission = "catalog:assembly-methods:manage",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7837)
                        },
                        new
                        {
                            RoleId = "0b42c919-01c0-4109-ba04-d848c45dc413",
                            Permission = "catalog:topics:view",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7838)
                        },
                        new
                        {
                            RoleId = "0b42c919-01c0-4109-ba04-d848c45dc413",
                            Permission = "catalog:topics:manage",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7839)
                        },
                        new
                        {
                            RoleId = "0b42c919-01c0-4109-ba04-d848c45dc413",
                            Permission = "catalog:materials:view",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7839)
                        },
                        new
                        {
                            RoleId = "0b42c919-01c0-4109-ba04-d848c45dc413",
                            Permission = "catalog:materials:manage",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7840)
                        },
                        new
                        {
                            RoleId = "0b42c919-01c0-4109-ba04-d848c45dc413",
                            Permission = "catalog:capabilities:view",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7840)
                        },
                        new
                        {
                            RoleId = "0b42c919-01c0-4109-ba04-d848c45dc413",
                            Permission = "catalog:capabilities:manage",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7841)
                        },
                        new
                        {
                            RoleId = "0b42c919-01c0-4109-ba04-d848c45dc413",
                            Permission = "instock:products:view",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7841)
                        },
                        new
                        {
                            RoleId = "0b42c919-01c0-4109-ba04-d848c45dc413",
                            Permission = "instock:orders:view",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7842)
                        },
                        new
                        {
                            RoleId = "1a0d505f-46d8-4aaf-92c7-71ba90443dcb",
                            Permission = "catalog:assembly-methods:view",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7844)
                        },
                        new
                        {
                            RoleId = "1a0d505f-46d8-4aaf-92c7-71ba90443dcb",
                            Permission = "catalog:assembly-methods:manage",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7845)
                        },
                        new
                        {
                            RoleId = "1a0d505f-46d8-4aaf-92c7-71ba90443dcb",
                            Permission = "catalog:topics:view",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7845)
                        },
                        new
                        {
                            RoleId = "1a0d505f-46d8-4aaf-92c7-71ba90443dcb",
                            Permission = "catalog:topics:manage",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7846)
                        },
                        new
                        {
                            RoleId = "1a0d505f-46d8-4aaf-92c7-71ba90443dcb",
                            Permission = "catalog:materials:view",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7846)
                        },
                        new
                        {
                            RoleId = "1a0d505f-46d8-4aaf-92c7-71ba90443dcb",
                            Permission = "catalog:materials:manage",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7847)
                        },
                        new
                        {
                            RoleId = "1a0d505f-46d8-4aaf-92c7-71ba90443dcb",
                            Permission = "catalog:capabilities:view",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7848)
                        },
                        new
                        {
                            RoleId = "1a0d505f-46d8-4aaf-92c7-71ba90443dcb",
                            Permission = "catalog:capabilities:manage",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7848)
                        },
                        new
                        {
                            RoleId = "1a0d505f-46d8-4aaf-92c7-71ba90443dcb",
                            Permission = "instock:products:view",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7849)
                        },
                        new
                        {
                            RoleId = "1a0d505f-46d8-4aaf-92c7-71ba90443dcb",
                            Permission = "instock:orders:view",
                            GrantedAt = new DateTime(2026, 2, 27, 7, 52, 19, 160, DateTimeKind.Utc).AddTicks(7938)
                        });
                });

            modelBuilder.Entity("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("identity_user", "identity");

                    b.HasData(
                        new
                        {
                            Id = "admin-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1d5366a7-43f2-405a-a85b-1c913c0c5b2f",
                            CreatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@puzkit3d.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            IsDeleted = false,
                            LastName = "Administrator",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@PUZKIT3D.COM",
                            NormalizedUserName = "ADMIN@PUZKIT3D.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPSfvsSKDzPCnkk8Mq3OFqUzOSemt4JjQU4Bg7a8oqcYFDNEuMFUlcClo72Obq8t9Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "52829083-e3e6-4328-bc06-ffa922a0abbc",
                            TwoFactorEnabled = false,
                            UserName = "admin@puzkit3d.com"
                        },
                        new
                        {
                            Id = "manager-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cc327c3a-bdcc-4b95-bce3-65177dfbe4fe",
                            CreatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manager@puzkit3d.com",
                            EmailConfirmed = true,
                            FirstName = "Business",
                            IsDeleted = false,
                            LastName = "Manager",
                            LockoutEnabled = false,
                            NormalizedEmail = "MANAGER@PUZKIT3D.COM",
                            NormalizedUserName = "MANAGER@PUZKIT3D.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDr0+IKdspm90K/Atw4QgWL7d72tlODQpuwXZJ4Vy5bpkB8K18GAeCpelTCsWnQRoQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6ffb607d-9395-49c2-9625-ed93885994b0",
                            TwoFactorEnabled = false,
                            UserName = "manager@puzkit3d.com"
                        },
                        new
                        {
                            Id = "staff-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9af8665d-1aca-4763-b814-9a25da7bd6fc",
                            CreatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff1@puzkit3d.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Staff",
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF1@PUZKIT3D.COM",
                            NormalizedUserName = "STAFF1@PUZKIT3D.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBIUHn2jIxsukbuuIsZVWDp/AJ4+374ehGUHJh4zxk91WeYH7VWljn3r6uFTJ392dA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2ae9876a-6240-4581-a894-21133bbbbe8c",
                            TwoFactorEnabled = false,
                            UserName = "staff1@puzkit3d.com"
                        },
                        new
                        {
                            Id = "staff-002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d693b4f9-d518-4fb0-92db-b61633590dad",
                            CreatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff2@puzkit3d.com",
                            EmailConfirmed = true,
                            FirstName = "Jane",
                            IsDeleted = false,
                            LastName = "Staff",
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF2@PUZKIT3D.COM",
                            NormalizedUserName = "STAFF2@PUZKIT3D.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIRgv1XVHWifHGFVB26ohtzsahQj3oY9/gGGUcZJ9Du1Akp0nTMNc8rB8q1v/GLBeQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "24030a5a-edc4-44a5-8dea-db68be5fe6d7",
                            TwoFactorEnabled = false,
                            UserName = "staff2@puzkit3d.com"
                        },
                        new
                        {
                            Id = "staff-003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5bd11bf3-e42b-4533-904a-e3558e15240f",
                            CreatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff3@puzkit3d.com",
                            EmailConfirmed = true,
                            FirstName = "Mike",
                            IsDeleted = false,
                            LastName = "Staff",
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF3@PUZKIT3D.COM",
                            NormalizedUserName = "STAFF3@PUZKIT3D.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDAZhxLEKyKNG+d5zJ2FOyGFXJPnM/uTev/GSjw6I0qVbidgJtfMl8SORarbMZc9LA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "10c189c9-c1bf-45a8-9c04-33f30aef2bc0",
                            TwoFactorEnabled = false,
                            UserName = "staff3@puzkit3d.com"
                        });
                });

            modelBuilder.Entity("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationUserPermission", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Permission")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GrantedBy")
                        .HasColumnType("text");

                    b.HasKey("UserId", "Permission");

                    b.ToTable("identity_user_permission", "identity");
                });

            modelBuilder.Entity("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("identity_user_role", "identity");

                    b.HasData(
                        new
                        {
                            UserId = "admin-001",
                            RoleId = "9b7da615-9c41-4700-92a9-ca17337c5724"
                        },
                        new
                        {
                            UserId = "manager-001",
                            RoleId = "0b42c919-01c0-4109-ba04-d848c45dc413"
                        },
                        new
                        {
                            UserId = "staff-001",
                            RoleId = "1a0d505f-46d8-4aaf-92c7-71ba90443dcb"
                        },
                        new
                        {
                            UserId = "staff-002",
                            RoleId = "1a0d505f-46d8-4aaf-92c7-71ba90443dcb"
                        },
                        new
                        {
                            UserId = "staff-003",
                            RoleId = "1a0d505f-46d8-4aaf-92c7-71ba90443dcb"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationRolePermission", b =>
                {
                    b.HasOne("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationUserPermission", b =>
                {
                    b.HasOne("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationUser", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationUserRole", b =>
                {
                    b.HasOne("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Navigation("UserPermissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
