// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PuzKit3D.SharedKernel.Infrastructure.Identity;

#nullable disable

namespace PuzKit3D.SharedKernel.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_identity_role_claim");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_identity_role_claim_role_id");

                    b.ToTable("identity_role_claim", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_identity_user_claim");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_identity_user_claim_user_id");

                    b.ToTable("identity_user_claim", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_identity_user_login");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_identity_user_login_user_id");

                    b.ToTable("identity_user_login", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_identity_user_token");

                    b.ToTable("identity_user_token", "identity");
                });

            modelBuilder.Entity("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_identity_role");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("identity_role", "identity");

                    b.HasData(
                        new
                        {
                            Id = "9b7da615-9c41-4700-92a9-ca17337c5724",
                            CreatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full system access",
                            Name = "System Administrator",
                            NormalizedName = "SYSTEM ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "0b42c919-01c0-4109-ba04-d848c45dc413",
                            CreatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-level business access",
                            Name = "Business Manager",
                            NormalizedName = "BUSINESS MANAGER"
                        },
                        new
                        {
                            Id = "1a0d505f-46d8-4aaf-92c7-71ba90443dcb",
                            CreatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Low-level business access",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = "f634ede8-7091-48da-a969-2bf90ef86f2c",
                            CreatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Standard customer access",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("District")
                        .HasColumnType("text")
                        .HasColumnName("district");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("Province")
                        .HasColumnType("text")
                        .HasColumnName("province");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("text")
                        .HasColumnName("street_address");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.Property<string>("Ward")
                        .HasColumnType("text")
                        .HasColumnName("ward");

                    b.HasKey("Id")
                        .HasName("pk_identity_user");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("identity_user", "identity");

                    b.HasData(
                        new
                        {
                            Id = "71ac7ce7-84e2-44f6-8765-209244d0cbb3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "A1B2C3D4-E5F6-7890-ABCD-EF1234567890",
                            CreatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@puzkit3d.com",
                            EmailConfirmed = true,
                            FirstName = "PuzKit3D",
                            IsDeleted = false,
                            LastName = "System Administrator",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@PUZKIT3D.COM",
                            NormalizedUserName = "ADMIN@PUZKIT3D.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJgIeRC3cRqtw8SBX3/jFxh3P6Bm2roRtAsMyAW3tpX8PZdIJ4XztKX4XtoGQl2LoQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "D5F8E9A1-2B3C-4D5E-6F7A-8B9C0D1E2F3A",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "admin@puzkit3d.com"
                        },
                        new
                        {
                            Id = "15e5d4ac-a548-4f8a-9846-5fddc79c79c2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "B2C3D4E5-F6A7-8901-BCDE-F23456789012",
                            CreatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manager@puzkit3d.com",
                            EmailConfirmed = true,
                            FirstName = "PuzKit3D",
                            IsDeleted = false,
                            LastName = "Business Manager",
                            LockoutEnabled = false,
                            NormalizedEmail = "MANAGER@PUZKIT3D.COM",
                            NormalizedUserName = "MANAGER@PUZKIT3D.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPJQdZ9oJoOjqjwgf6UGn6KNrUEgUHhOpgXcWr+xyaLpq7cNOrpSOT+o+SzFb//JnQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "B6E7F8A9-1C2D-3E4F-5A6B-7C8D9E0F1A2B",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "manager@puzkit3d.com"
                        },
                        new
                        {
                            Id = "10fa5863-e39c-4876-856e-5c4cfbd321dc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "C3D4E5F6-A7B8-9012-CDEF-345678901234",
                            CreatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff@puzkit3d.com",
                            EmailConfirmed = true,
                            FirstName = "PuzKit3D",
                            IsDeleted = false,
                            LastName = "Staff",
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF@PUZKIT3D.COM",
                            NormalizedUserName = "STAFF@PUZKIT3D.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDDvoSy5VkPjPmpuil2KqhCZ0MQuZvvMHE0qGwJ/UBVSzpqRUPcDtjIp4wL7xKKPxw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "C7D8E9F0-1A2B-3C4D-5E6F-7A8B9C0D1E2F",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "staff@puzkit3d.com"
                        },
                        new
                        {
                            Id = "21d3261d-9ab4-45b9-b6cd-fba0231d285c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "D4E5F6A7-B8C9-0123-DEF4-567890123456",
                            CreatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer@puzkit3d.com",
                            EmailConfirmed = true,
                            FirstName = "PuzKit3D",
                            IsDeleted = false,
                            LastName = "Customer",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER@PUZKIT3D.COM",
                            NormalizedUserName = "CUSTOMER@PUZKIT3D.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPGgQLpDWzR/Vp/zwUKsVelbluVZvPPUDSvzd+BLZSLqUMFYjWQ3mw0ZQVHyK0cchQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "D8E9F0A1-2B3C-4D5E-6F7A-8B9C0D1E2F3A",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "customer@puzkit3d.com"
                        });
                });

            modelBuilder.Entity("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_identity_user_role");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_identity_user_role_role_id");

                    b.ToTable("identity_user_role", "identity");

                    b.HasData(
                        new
                        {
                            UserId = "71ac7ce7-84e2-44f6-8765-209244d0cbb3",
                            RoleId = "9b7da615-9c41-4700-92a9-ca17337c5724"
                        },
                        new
                        {
                            UserId = "15e5d4ac-a548-4f8a-9846-5fddc79c79c2",
                            RoleId = "0b42c919-01c0-4109-ba04-d848c45dc413"
                        },
                        new
                        {
                            UserId = "10fa5863-e39c-4876-856e-5c4cfbd321dc",
                            RoleId = "1a0d505f-46d8-4aaf-92c7-71ba90443dcb"
                        },
                        new
                        {
                            UserId = "21d3261d-9ab4-45b9-b6cd-fba0231d285c",
                            RoleId = "f634ede8-7091-48da-a969-2bf90ef86f2c"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_role_claim_identity_role_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_user_claim_identity_user_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_user_login_identity_user_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_user_token_identity_user_user_id");
                });

            modelBuilder.Entity("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationUserRole", b =>
                {
                    b.HasOne("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_user_role_identity_role_role_id");

                    b.HasOne("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_user_role_identity_user_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PuzKit3D.SharedKernel.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
