// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PuzKit3D.Modules.CustomDesign.Persistence;

#nullable disable

namespace PuzKit3D.Modules.CustomDesign.Persistence.Migrations
{
    [DbContext(typeof(CustomDesignDbContext))]
    partial class CustomDesignDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("custome_design")
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PuzKit3D.Modules.CustomDesign.Domain.Entities.CustomDesignAssets.CustomDesignAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomDesignRequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("custom_design_requirement_id");

                    b.Property<bool>("IsFinalDesign")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_final_design");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Rough3DModel")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rough3d_model");

                    b.Property<string>("Rough3DModelTaskId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rough3d_model_task_id");

                    b.Property<string>("SketchTaskId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("sketch_task_id");

                    b.Property<string>("Sketches")
                        .HasColumnType("text")
                        .HasColumnName("sketches");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_custom_design_assets");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ___custom_design_asset___code");

                    b.ToTable("custom_design_assets", "custome_design");
                });

            modelBuilder.Entity("PuzKit3D.Modules.CustomDesign.Domain.Entities.CustomDesignRequests.CustomDesignRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomDesignRequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("custom_design_requirement_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("DesiredDeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("desired_delivery_date");

                    b.Property<decimal>("DesiredHeightMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("desired_height_mm");

                    b.Property<decimal>("DesiredLengthMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("desired_length_mm");

                    b.Property<int>("DesiredPartQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("desired_part_quantity");

                    b.Property<int>("DesiredQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("desired_quantity");

                    b.Property<decimal>("DesiredWidthMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("desired_width_mm");

                    b.Property<string>("Sketches")
                        .HasColumnType("text")
                        .HasColumnName("sketches");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<decimal>("TargetBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("target_budget");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsedSupportConceptDesignTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("used_support_concept_design_time");

                    b.HasKey("Id")
                        .HasName("pk_custom_design_requests");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ___custom_design_request___code");

                    b.ToTable("custom_design_requests", "custome_design");
                });

            modelBuilder.Entity("PuzKit3D.Modules.CustomDesign.Domain.Entities.CustomDesignRequirements.CustomDesignRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssemblyMethodId")
                        .HasColumnType("uuid")
                        .HasColumnName("assembly_method_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<int>("MaxPartQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("max_part_quantity");

                    b.Property<int>("MinPartQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("min_part_quantity");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_custom_design_requirements");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ___custom_design_requirement___code");

                    b.ToTable("custom_design_requirements", "custome_design");
                });

            modelBuilder.Entity("PuzKit3D.Modules.CustomDesign.Domain.Entities.Replicas.AssemblyMethodReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assembly_method_replicas");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UK__assembly_method_replica__slug");

                    b.ToTable("assembly_method_replicas", "custome_design");
                });

            modelBuilder.Entity("PuzKit3D.Modules.CustomDesign.Domain.Entities.Replicas.CapabilityReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_capability_replicas");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UK__capability_replica__slug");

                    b.ToTable("capability_replicas", "custome_design");
                });

            modelBuilder.Entity("PuzKit3D.Modules.CustomDesign.Domain.Entities.Replicas.MaterialReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_material_replicas");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UK__material_replica__slug");

                    b.ToTable("material_replicas", "custome_design");
                });

            modelBuilder.Entity("PuzKit3D.Modules.CustomDesign.Domain.Entities.Replicas.TopicReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_topic_replicas");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UK__topic_replica__slug");

                    b.ToTable("topic_replicas", "custome_design");
                });

            modelBuilder.Entity("PuzKit3D.Modules.CustomDesign.Domain.Entities.RequirementCapabilityDetails.RequirementCapabilityDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CapabilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("capability_id");

                    b.Property<Guid>("CustomDesignRequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("custom_design_requirement_id");

                    b.HasKey("Id")
                        .HasName("pk_requirement_capability_details");

                    b.HasIndex("CustomDesignRequirementId", "CapabilityId")
                        .IsUnique()
                        .HasDatabaseName("UQ___requirement_capability_detail___requirement_id__capability_id");

                    b.ToTable("requirement_capability_details", "custome_design");
                });
#pragma warning restore 612, 618
        }
    }
}
