// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PuzKit3D.Modules.Delivery.Persistence;

#nullable disable

namespace PuzKit3D.Modules.Delivery.Persistence.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    [Migration("20260411144334_InitModule")]
    partial class InitModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("delivery")
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PuzKit3D.Modules.Delivery.Domain.Entities.DeliveryTrackings.DeliveryTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("DeliveryOrderCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("delivery_order_code");

                    b.Property<DateTime>("ExpectedDeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_delivery_date");

                    b.Property<string>("HandOverImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("hand_over_image_url");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupportTicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("support_ticket_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_delivery_trackings");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_delivery_trackings_created_at");

                    b.HasIndex("DeliveryOrderCode")
                        .IsUnique()
                        .HasDatabaseName("ix_delivery_trackings_delivery_order_code");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_delivery_trackings_order_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_delivery_trackings_status");

                    b.HasIndex("SupportTicketId")
                        .HasDatabaseName("ix_delivery_trackings_support_ticket_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_delivery_trackings_type");

                    b.ToTable("delivery_trackings", "delivery");
                });

            modelBuilder.Entity("PuzKit3D.Modules.Delivery.Domain.Entities.DeliveryTrackings.DeliveryTrackingDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeliveryTrackingId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_tracking_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_delivery_tracking_details");

                    b.HasIndex("DeliveryTrackingId")
                        .HasDatabaseName("ix_delivery_tracking_details_delivery_tracking_id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_delivery_tracking_details_item_id");

                    b.ToTable("delivery_tracking_details", "delivery");
                });

            modelBuilder.Entity("PuzKit3D.Modules.Delivery.Domain.Entities.Replicas.DriveReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<int?>("MinVolume")
                        .HasColumnType("integer")
                        .HasColumnName("min_volume");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_in_stock");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_drive_replicas");

                    b.ToTable("drive_replicas", "delivery");
                });

            modelBuilder.Entity("PuzKit3D.Modules.Delivery.Domain.Entities.Replicas.OrderDetailReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<string>("VariantName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("variant_name");

                    b.HasKey("Id")
                        .HasName("pk_order_detail_replicas");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_detail_replicas_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_detail_replicas_product_id");

                    b.ToTable("order_detail_replicas", "delivery");
                });

            modelBuilder.Entity("PuzKit3D.Modules.Delivery.Domain.Entities.Replicas.OrderReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_order_replicas");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_order_replicas_customer_id");

                    b.ToTable("order_replicas", "delivery");
                });

            modelBuilder.Entity("PuzKit3D.Modules.Delivery.Domain.Entities.Replicas.PartReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InstockProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("instock_product_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<string>("PartType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("part_type");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_part_replicas");

                    b.ToTable("part_replicas", "delivery");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0001-0000-0000-000000000000"),
                            Code = "PAR0001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Lion Part 1",
                            PartType = "Structural",
                            Quantity = 10,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0001-0001-0000-000000000000"),
                            Code = "PAR0002",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Lion Part 2",
                            PartType = "Mechanical",
                            Quantity = 15,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0001-0002-0000-000000000000"),
                            Code = "PAR0003",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Lion Part 3",
                            PartType = "Decorative",
                            Quantity = 20,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0001-0003-0000-000000000000"),
                            Code = "PAR0004",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Lion Part 4",
                            PartType = "Structural",
                            Quantity = 25,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0001-0004-0000-000000000000"),
                            Code = "PAR0005",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Lion Part 5",
                            PartType = "Mechanical",
                            Quantity = 30,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0001-0005-0000-000000000000"),
                            Code = "PAR0006",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Lion Part 6",
                            PartType = "Decorative",
                            Quantity = 35,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0001-0006-0000-000000000000"),
                            Code = "PAR0007",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Lion Part 7",
                            PartType = "Structural",
                            Quantity = 40,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0001-0007-0000-000000000000"),
                            Code = "PAR0008",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Lion Part 8",
                            PartType = "Mechanical",
                            Quantity = 45,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0001-0008-0000-000000000000"),
                            Code = "PAR0009",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Lion Part 9",
                            PartType = "Decorative",
                            Quantity = 50,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0001-0009-0000-000000000000"),
                            Code = "PAR0010",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Lion Part 10",
                            PartType = "Structural",
                            Quantity = 55,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0002-0000-0000-000000000000"),
                            Code = "PAR0011",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Elephant Part 1",
                            PartType = "Structural",
                            Quantity = 10,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0002-0001-0000-000000000000"),
                            Code = "PAR0012",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Elephant Part 2",
                            PartType = "Mechanical",
                            Quantity = 15,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0002-0002-0000-000000000000"),
                            Code = "PAR0013",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Elephant Part 3",
                            PartType = "Decorative",
                            Quantity = 20,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0002-0003-0000-000000000000"),
                            Code = "PAR0014",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Elephant Part 4",
                            PartType = "Structural",
                            Quantity = 25,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0002-0004-0000-000000000000"),
                            Code = "PAR0015",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Elephant Part 5",
                            PartType = "Mechanical",
                            Quantity = 30,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0002-0005-0000-000000000000"),
                            Code = "PAR0016",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Elephant Part 6",
                            PartType = "Decorative",
                            Quantity = 35,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0002-0006-0000-000000000000"),
                            Code = "PAR0017",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Elephant Part 7",
                            PartType = "Structural",
                            Quantity = 40,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0002-0007-0000-000000000000"),
                            Code = "PAR0018",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Elephant Part 8",
                            PartType = "Mechanical",
                            Quantity = 45,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0002-0008-0000-000000000000"),
                            Code = "PAR0019",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Elephant Part 9",
                            PartType = "Decorative",
                            Quantity = 50,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0002-0009-0000-000000000000"),
                            Code = "PAR0020",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Elephant Part 10",
                            PartType = "Structural",
                            Quantity = 55,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0003-0000-0000-000000000000"),
                            Code = "PAR0021",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Eagle Part 1",
                            PartType = "Structural",
                            Quantity = 10,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0003-0001-0000-000000000000"),
                            Code = "PAR0022",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Eagle Part 2",
                            PartType = "Mechanical",
                            Quantity = 15,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0003-0002-0000-000000000000"),
                            Code = "PAR0023",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Eagle Part 3",
                            PartType = "Decorative",
                            Quantity = 20,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0003-0003-0000-000000000000"),
                            Code = "PAR0024",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Eagle Part 4",
                            PartType = "Structural",
                            Quantity = 25,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0003-0004-0000-000000000000"),
                            Code = "PAR0025",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Eagle Part 5",
                            PartType = "Mechanical",
                            Quantity = 30,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0003-0005-0000-000000000000"),
                            Code = "PAR0026",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Eagle Part 6",
                            PartType = "Decorative",
                            Quantity = 35,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0003-0006-0000-000000000000"),
                            Code = "PAR0027",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Eagle Part 7",
                            PartType = "Structural",
                            Quantity = 40,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0003-0007-0000-000000000000"),
                            Code = "PAR0028",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Eagle Part 8",
                            PartType = "Mechanical",
                            Quantity = 45,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0003-0008-0000-000000000000"),
                            Code = "PAR0029",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Eagle Part 9",
                            PartType = "Decorative",
                            Quantity = 50,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0003-0009-0000-000000000000"),
                            Code = "PAR0030",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Eagle Part 10",
                            PartType = "Structural",
                            Quantity = 55,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0004-0000-0000-000000000000"),
                            Code = "PAR0031",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Name = "Sports Car Part 1",
                            PartType = "Structural",
                            Quantity = 10,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0004-0001-0000-000000000000"),
                            Code = "PAR0032",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Name = "Sports Car Part 2",
                            PartType = "Mechanical",
                            Quantity = 15,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0004-0002-0000-000000000000"),
                            Code = "PAR0033",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Name = "Sports Car Part 3",
                            PartType = "Decorative",
                            Quantity = 20,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0004-0003-0000-000000000000"),
                            Code = "PAR0034",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Name = "Sports Car Part 4",
                            PartType = "Structural",
                            Quantity = 25,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0004-0004-0000-000000000000"),
                            Code = "PAR0035",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Name = "Sports Car Part 5",
                            PartType = "Mechanical",
                            Quantity = 30,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0004-0005-0000-000000000000"),
                            Code = "PAR0036",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Name = "Sports Car Part 6",
                            PartType = "Decorative",
                            Quantity = 35,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0004-0006-0000-000000000000"),
                            Code = "PAR0037",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Name = "Sports Car Part 7",
                            PartType = "Structural",
                            Quantity = 40,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0004-0007-0000-000000000000"),
                            Code = "PAR0038",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Name = "Sports Car Part 8",
                            PartType = "Mechanical",
                            Quantity = 45,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0004-0008-0000-000000000000"),
                            Code = "PAR0039",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Name = "Sports Car Part 9",
                            PartType = "Decorative",
                            Quantity = 50,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0004-0009-0000-000000000000"),
                            Code = "PAR0040",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Name = "Sports Car Part 10",
                            PartType = "Structural",
                            Quantity = 55,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0005-0000-0000-000000000000"),
                            Code = "PAR0041",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Name = "Airplane Part 1",
                            PartType = "Structural",
                            Quantity = 10,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0005-0001-0000-000000000000"),
                            Code = "PAR0042",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Name = "Airplane Part 2",
                            PartType = "Mechanical",
                            Quantity = 15,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0005-0002-0000-000000000000"),
                            Code = "PAR0043",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Name = "Airplane Part 3",
                            PartType = "Decorative",
                            Quantity = 20,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0005-0003-0000-000000000000"),
                            Code = "PAR0044",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Name = "Airplane Part 4",
                            PartType = "Structural",
                            Quantity = 25,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0005-0004-0000-000000000000"),
                            Code = "PAR0045",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Name = "Airplane Part 5",
                            PartType = "Mechanical",
                            Quantity = 30,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0005-0005-0000-000000000000"),
                            Code = "PAR0046",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Name = "Airplane Part 6",
                            PartType = "Decorative",
                            Quantity = 35,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0005-0006-0000-000000000000"),
                            Code = "PAR0047",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Name = "Airplane Part 7",
                            PartType = "Structural",
                            Quantity = 40,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0005-0007-0000-000000000000"),
                            Code = "PAR0048",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Name = "Airplane Part 8",
                            PartType = "Mechanical",
                            Quantity = 45,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0005-0008-0000-000000000000"),
                            Code = "PAR0049",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Name = "Airplane Part 9",
                            PartType = "Decorative",
                            Quantity = 50,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0005-0009-0000-000000000000"),
                            Code = "PAR0050",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000005"),
                            Name = "Airplane Part 10",
                            PartType = "Structural",
                            Quantity = 55,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0006-0000-0000-000000000000"),
                            Code = "PAR0051",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Name = "Motorcycle Part 1",
                            PartType = "Structural",
                            Quantity = 10,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0006-0001-0000-000000000000"),
                            Code = "PAR0052",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Name = "Motorcycle Part 2",
                            PartType = "Mechanical",
                            Quantity = 15,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0006-0002-0000-000000000000"),
                            Code = "PAR0053",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Name = "Motorcycle Part 3",
                            PartType = "Decorative",
                            Quantity = 20,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0006-0003-0000-000000000000"),
                            Code = "PAR0054",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Name = "Motorcycle Part 4",
                            PartType = "Structural",
                            Quantity = 25,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0006-0004-0000-000000000000"),
                            Code = "PAR0055",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Name = "Motorcycle Part 5",
                            PartType = "Mechanical",
                            Quantity = 30,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0006-0005-0000-000000000000"),
                            Code = "PAR0056",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Name = "Motorcycle Part 6",
                            PartType = "Decorative",
                            Quantity = 35,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0006-0006-0000-000000000000"),
                            Code = "PAR0057",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Name = "Motorcycle Part 7",
                            PartType = "Structural",
                            Quantity = 40,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0006-0007-0000-000000000000"),
                            Code = "PAR0058",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Name = "Motorcycle Part 8",
                            PartType = "Mechanical",
                            Quantity = 45,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0006-0008-0000-000000000000"),
                            Code = "PAR0059",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Name = "Motorcycle Part 9",
                            PartType = "Decorative",
                            Quantity = 50,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0006-0009-0000-000000000000"),
                            Code = "PAR0060",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000006"),
                            Name = "Motorcycle Part 10",
                            PartType = "Structural",
                            Quantity = 55,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0007-0000-0000-000000000000"),
                            Code = "PAR0061",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000007"),
                            Name = "Tiger Part 1",
                            PartType = "Structural",
                            Quantity = 10,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0007-0001-0000-000000000000"),
                            Code = "PAR0062",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000007"),
                            Name = "Tiger Part 2",
                            PartType = "Mechanical",
                            Quantity = 15,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0007-0002-0000-000000000000"),
                            Code = "PAR0063",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000007"),
                            Name = "Tiger Part 3",
                            PartType = "Decorative",
                            Quantity = 20,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0007-0003-0000-000000000000"),
                            Code = "PAR0064",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000007"),
                            Name = "Tiger Part 4",
                            PartType = "Structural",
                            Quantity = 25,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0007-0004-0000-000000000000"),
                            Code = "PAR0065",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000007"),
                            Name = "Tiger Part 5",
                            PartType = "Mechanical",
                            Quantity = 30,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0007-0005-0000-000000000000"),
                            Code = "PAR0066",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000007"),
                            Name = "Tiger Part 6",
                            PartType = "Decorative",
                            Quantity = 35,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0007-0006-0000-000000000000"),
                            Code = "PAR0067",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000007"),
                            Name = "Tiger Part 7",
                            PartType = "Structural",
                            Quantity = 40,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0007-0007-0000-000000000000"),
                            Code = "PAR0068",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000007"),
                            Name = "Tiger Part 8",
                            PartType = "Mechanical",
                            Quantity = 45,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0007-0008-0000-000000000000"),
                            Code = "PAR0069",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000007"),
                            Name = "Tiger Part 9",
                            PartType = "Decorative",
                            Quantity = 50,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0007-0009-0000-000000000000"),
                            Code = "PAR0070",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000007"),
                            Name = "Tiger Part 10",
                            PartType = "Structural",
                            Quantity = 55,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0008-0000-0000-000000000000"),
                            Code = "PAR0071",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000008"),
                            Name = "Dolphin Part 1",
                            PartType = "Structural",
                            Quantity = 10,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0008-0001-0000-000000000000"),
                            Code = "PAR0072",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000008"),
                            Name = "Dolphin Part 2",
                            PartType = "Mechanical",
                            Quantity = 15,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0008-0002-0000-000000000000"),
                            Code = "PAR0073",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000008"),
                            Name = "Dolphin Part 3",
                            PartType = "Decorative",
                            Quantity = 20,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0008-0003-0000-000000000000"),
                            Code = "PAR0074",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000008"),
                            Name = "Dolphin Part 4",
                            PartType = "Structural",
                            Quantity = 25,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0008-0004-0000-000000000000"),
                            Code = "PAR0075",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000008"),
                            Name = "Dolphin Part 5",
                            PartType = "Mechanical",
                            Quantity = 30,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0008-0005-0000-000000000000"),
                            Code = "PAR0076",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000008"),
                            Name = "Dolphin Part 6",
                            PartType = "Decorative",
                            Quantity = 35,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0008-0006-0000-000000000000"),
                            Code = "PAR0077",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000008"),
                            Name = "Dolphin Part 7",
                            PartType = "Structural",
                            Quantity = 40,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0008-0007-0000-000000000000"),
                            Code = "PAR0078",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000008"),
                            Name = "Dolphin Part 8",
                            PartType = "Mechanical",
                            Quantity = 45,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0008-0008-0000-000000000000"),
                            Code = "PAR0079",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000008"),
                            Name = "Dolphin Part 9",
                            PartType = "Decorative",
                            Quantity = 50,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0008-0009-0000-000000000000"),
                            Code = "PAR0080",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000008"),
                            Name = "Dolphin Part 10",
                            PartType = "Structural",
                            Quantity = 55,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0009-0000-0000-000000000000"),
                            Code = "PAR0081",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000009"),
                            Name = "Helicopter Part 1",
                            PartType = "Structural",
                            Quantity = 10,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0009-0001-0000-000000000000"),
                            Code = "PAR0082",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000009"),
                            Name = "Helicopter Part 2",
                            PartType = "Mechanical",
                            Quantity = 15,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0009-0002-0000-000000000000"),
                            Code = "PAR0083",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000009"),
                            Name = "Helicopter Part 3",
                            PartType = "Decorative",
                            Quantity = 20,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0009-0003-0000-000000000000"),
                            Code = "PAR0084",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000009"),
                            Name = "Helicopter Part 4",
                            PartType = "Structural",
                            Quantity = 25,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0009-0004-0000-000000000000"),
                            Code = "PAR0085",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000009"),
                            Name = "Helicopter Part 5",
                            PartType = "Mechanical",
                            Quantity = 30,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0009-0005-0000-000000000000"),
                            Code = "PAR0086",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000009"),
                            Name = "Helicopter Part 6",
                            PartType = "Decorative",
                            Quantity = 35,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0009-0006-0000-000000000000"),
                            Code = "PAR0087",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000009"),
                            Name = "Helicopter Part 7",
                            PartType = "Structural",
                            Quantity = 40,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0009-0007-0000-000000000000"),
                            Code = "PAR0088",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000009"),
                            Name = "Helicopter Part 8",
                            PartType = "Mechanical",
                            Quantity = 45,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0009-0008-0000-000000000000"),
                            Code = "PAR0089",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000009"),
                            Name = "Helicopter Part 9",
                            PartType = "Decorative",
                            Quantity = 50,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0009-0009-0000-000000000000"),
                            Code = "PAR0090",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000009"),
                            Name = "Helicopter Part 10",
                            PartType = "Structural",
                            Quantity = 55,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0010-0000-0000-000000000000"),
                            Code = "PAR0091",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Name = "Dragon Part 1",
                            PartType = "Structural",
                            Quantity = 10,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0010-0001-0000-000000000000"),
                            Code = "PAR0092",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Name = "Dragon Part 2",
                            PartType = "Mechanical",
                            Quantity = 15,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0010-0002-0000-000000000000"),
                            Code = "PAR0093",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Name = "Dragon Part 3",
                            PartType = "Decorative",
                            Quantity = 20,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0010-0003-0000-000000000000"),
                            Code = "PAR0094",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Name = "Dragon Part 4",
                            PartType = "Structural",
                            Quantity = 25,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0010-0004-0000-000000000000"),
                            Code = "PAR0095",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Name = "Dragon Part 5",
                            PartType = "Mechanical",
                            Quantity = 30,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0010-0005-0000-000000000000"),
                            Code = "PAR0096",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Name = "Dragon Part 6",
                            PartType = "Decorative",
                            Quantity = 35,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0010-0006-0000-000000000000"),
                            Code = "PAR0097",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Name = "Dragon Part 7",
                            PartType = "Structural",
                            Quantity = 40,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0010-0007-0000-000000000000"),
                            Code = "PAR0098",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Name = "Dragon Part 8",
                            PartType = "Mechanical",
                            Quantity = 45,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0010-0008-0000-000000000000"),
                            Code = "PAR0099",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Name = "Dragon Part 9",
                            PartType = "Decorative",
                            Quantity = 50,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("50000000-0010-0009-0000-000000000000"),
                            Code = "PAR0100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstockProductId = new Guid("10000000-0000-0000-0000-000000000010"),
                            Name = "Dragon Part 10",
                            PartType = "Structural",
                            Quantity = 55,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PuzKit3D.Modules.Delivery.Domain.Entities.Replicas.SupportTicketDetailReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Note")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_id");

                    b.Property<Guid?>("PartId")
                        .HasColumnType("uuid")
                        .HasColumnName("part_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SupportTicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("support_ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_support_ticket_detail_replicas");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("ix_support_ticket_detail_replicas_order_item_id");

                    b.HasIndex("SupportTicketId")
                        .HasDatabaseName("ix_support_ticket_detail_replicas_support_ticket_id");

                    b.ToTable("support_ticket_detail_replicas", "delivery");
                });

            modelBuilder.Entity("PuzKit3D.Modules.Delivery.Domain.Entities.Replicas.SupportTicketReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Proof")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("proof");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_support_ticket_replicas");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_support_ticket_replicas_order_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_support_ticket_replicas_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_support_ticket_replicas_user_id");

                    b.ToTable("support_ticket_replicas", "delivery");
                });

            modelBuilder.Entity("PuzKit3D.Modules.Delivery.Domain.Entities.Replicas.UserReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("district");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("province");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("street_address");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Ward")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ward");

                    b.HasKey("Id")
                        .HasName("pk_user_replicas");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UK__user_replica__email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("UK__user_replica__phone_number");

                    b.ToTable("user_replicas", "delivery");
                });

            modelBuilder.Entity("PuzKit3D.Modules.Delivery.Domain.Entities.DeliveryTrackings.DeliveryTrackingDetail", b =>
                {
                    b.HasOne("PuzKit3D.Modules.Delivery.Domain.Entities.DeliveryTrackings.DeliveryTracking", null)
                        .WithMany("Details")
                        .HasForeignKey("DeliveryTrackingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_tracking_details_delivery_trackings_delivery_track");
                });

            modelBuilder.Entity("PuzKit3D.Modules.Delivery.Domain.Entities.Replicas.SupportTicketDetailReplica", b =>
                {
                    b.HasOne("PuzKit3D.Modules.Delivery.Domain.Entities.Replicas.SupportTicketReplica", null)
                        .WithMany("Details")
                        .HasForeignKey("SupportTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_support_ticket_detail_replicas_support_ticket_replicas_supp");
                });

            modelBuilder.Entity("PuzKit3D.Modules.Delivery.Domain.Entities.DeliveryTrackings.DeliveryTracking", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("PuzKit3D.Modules.Delivery.Domain.Entities.Replicas.SupportTicketReplica", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
