// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PuzKit3D.Modules.Cart.Persistence;

#nullable disable

namespace PuzKit3D.Modules.Cart.Persistence.Migrations
{
    [DbContext(typeof(CartDbContext))]
    [Migration("20260318045456_InitModule")]
    partial class InitModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cart")
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PuzKit3D.Modules.Cart.Domain.Entities.Carts.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CartType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cart_type");

                    b.Property<int>("TotalItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_item");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_carts");

                    b.HasIndex("UserId", "CartType")
                        .IsUnique()
                        .HasDatabaseName("CUK___cart___user_id__cart_type");

                    b.ToTable("carts", "cart");
                });

            modelBuilder.Entity("PuzKit3D.Modules.Cart.Domain.Entities.Carts.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid")
                        .HasColumnName("cart_id");

                    b.Property<Guid?>("InStockProductPriceDetailId")
                        .HasColumnType("uuid")
                        .HasColumnName("in_stock_product_price_detail_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_cart_items");

                    b.HasIndex("CartId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("CUK___cart___cart_id__item_id");

                    b.ToTable("cart_items", "cart");
                });

            modelBuilder.Entity("PuzKit3D.Modules.Cart.Domain.Entities.Replicas.InStockInventoryReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InStockProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("in_stock_product_variant_id");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("total_quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_in_stock_inventory_replicas");

                    b.HasIndex("InStockProductVariantId")
                        .HasDatabaseName("ix_instock_inventory_replica_instock_product_variant_id");

                    b.ToTable("in_stock_inventory_replicas", "cart");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0001-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductVariantId = new Guid("20000000-0001-0000-0000-000000000001"),
                            TotalQuantity = 75,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0002-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductVariantId = new Guid("20000000-0001-0000-0000-000000000002"),
                            TotalQuantity = 83,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0003-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductVariantId = new Guid("20000000-0002-0000-0000-000000000001"),
                            TotalQuantity = 162,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0004-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductVariantId = new Guid("20000000-0003-0000-0000-000000000001"),
                            TotalQuantity = 152,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0005-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductVariantId = new Guid("20000000-0003-0000-0000-000000000002"),
                            TotalQuantity = 123,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0006-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductVariantId = new Guid("20000000-0004-0000-0000-000000000001"),
                            TotalQuantity = 167,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0007-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductVariantId = new Guid("20000000-0004-0000-0000-000000000002"),
                            TotalQuantity = 52,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0008-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductVariantId = new Guid("20000000-0005-0000-0000-000000000001"),
                            TotalQuantity = 99,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0009-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductVariantId = new Guid("20000000-0006-0000-0000-000000000001"),
                            TotalQuantity = 13,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0010-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductVariantId = new Guid("20000000-0006-0000-0000-000000000002"),
                            TotalQuantity = 186,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0011-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductVariantId = new Guid("20000000-0007-0000-0000-000000000001"),
                            TotalQuantity = 78,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0012-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductVariantId = new Guid("20000000-0008-0000-0000-000000000001"),
                            TotalQuantity = 143,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0013-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductVariantId = new Guid("20000000-0008-0000-0000-000000000002"),
                            TotalQuantity = 35,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0014-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductVariantId = new Guid("20000000-0009-0000-0000-000000000001"),
                            TotalQuantity = 117,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0015-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductVariantId = new Guid("20000000-0010-0000-0000-000000000001"),
                            TotalQuantity = 10,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("40000000-0016-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductVariantId = new Guid("20000000-0010-0000-0000-000000000002"),
                            TotalQuantity = 185,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PuzKit3D.Modules.Cart.Domain.Entities.Replicas.InStockPriceReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTime>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_in_stock_price_replicas");

                    b.ToTable("in_stock_price_replicas", "cart");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999991"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveFrom = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2099, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Standard",
                            Priority = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999992"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveTo = new DateTime(2026, 7, 1, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Sale Summer Vacation",
                            Priority = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PuzKit3D.Modules.Cart.Domain.Entities.Replicas.InStockProductPriceDetailReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InStockPriceId")
                        .HasColumnType("uuid")
                        .HasColumnName("in_stock_price_id");

                    b.Property<Guid>("InStockProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("in_stock_product_variant_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_in_stock_product_price_detail_replicas");

                    b.HasIndex("InStockPriceId", "InStockProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("CUK___instock_product_price_detail_replica___instock_price_id__instock_product_variant_id");

                    b.ToTable("in_stock_product_price_detail_replicas", "cart");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0001-1000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999991"),
                            InStockProductVariantId = new Guid("20000000-0001-0000-0000-000000000001"),
                            IsActive = true,
                            UnitPrice = 745000m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0001-2000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999992"),
                            InStockProductVariantId = new Guid("20000000-0001-0000-0000-000000000001"),
                            IsActive = true,
                            UnitPrice = 596000.0m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0002-1000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999991"),
                            InStockProductVariantId = new Guid("20000000-0001-0000-0000-000000000002"),
                            IsActive = true,
                            UnitPrice = 419000m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0002-2000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999992"),
                            InStockProductVariantId = new Guid("20000000-0001-0000-0000-000000000002"),
                            IsActive = true,
                            UnitPrice = 335200.0m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0003-1000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999991"),
                            InStockProductVariantId = new Guid("20000000-0002-0000-0000-000000000001"),
                            IsActive = true,
                            UnitPrice = 268000m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0003-2000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999992"),
                            InStockProductVariantId = new Guid("20000000-0002-0000-0000-000000000001"),
                            IsActive = true,
                            UnitPrice = 214400.0m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0004-1000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999991"),
                            InStockProductVariantId = new Guid("20000000-0003-0000-0000-000000000001"),
                            IsActive = true,
                            UnitPrice = 869000m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0004-2000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999992"),
                            InStockProductVariantId = new Guid("20000000-0003-0000-0000-000000000001"),
                            IsActive = true,
                            UnitPrice = 695200.0m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0005-1000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999991"),
                            InStockProductVariantId = new Guid("20000000-0003-0000-0000-000000000002"),
                            IsActive = true,
                            UnitPrice = 648000m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0005-2000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999992"),
                            InStockProductVariantId = new Guid("20000000-0003-0000-0000-000000000002"),
                            IsActive = true,
                            UnitPrice = 518400.0m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0006-1000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999991"),
                            InStockProductVariantId = new Guid("20000000-0004-0000-0000-000000000001"),
                            IsActive = true,
                            UnitPrice = 356000m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0006-2000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999992"),
                            InStockProductVariantId = new Guid("20000000-0004-0000-0000-000000000001"),
                            IsActive = true,
                            UnitPrice = 284800.0m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0007-1000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999991"),
                            InStockProductVariantId = new Guid("20000000-0004-0000-0000-000000000002"),
                            IsActive = true,
                            UnitPrice = 909000m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0007-2000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999992"),
                            InStockProductVariantId = new Guid("20000000-0004-0000-0000-000000000002"),
                            IsActive = true,
                            UnitPrice = 727200.0m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0008-1000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999991"),
                            InStockProductVariantId = new Guid("20000000-0005-0000-0000-000000000001"),
                            IsActive = true,
                            UnitPrice = 631000m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0008-2000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999992"),
                            InStockProductVariantId = new Guid("20000000-0005-0000-0000-000000000001"),
                            IsActive = true,
                            UnitPrice = 504800.0m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0009-1000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999991"),
                            InStockProductVariantId = new Guid("20000000-0006-0000-0000-000000000001"),
                            IsActive = true,
                            UnitPrice = 531000m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0009-2000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999992"),
                            InStockProductVariantId = new Guid("20000000-0006-0000-0000-000000000001"),
                            IsActive = true,
                            UnitPrice = 424800.0m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0010-1000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999991"),
                            InStockProductVariantId = new Guid("20000000-0006-0000-0000-000000000002"),
                            IsActive = true,
                            UnitPrice = 615000m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0010-2000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999992"),
                            InStockProductVariantId = new Guid("20000000-0006-0000-0000-000000000002"),
                            IsActive = true,
                            UnitPrice = 492000.0m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0011-1000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999991"),
                            InStockProductVariantId = new Guid("20000000-0007-0000-0000-000000000001"),
                            IsActive = true,
                            UnitPrice = 704000m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0011-2000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999992"),
                            InStockProductVariantId = new Guid("20000000-0007-0000-0000-000000000001"),
                            IsActive = true,
                            UnitPrice = 563200.0m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0012-1000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999991"),
                            InStockProductVariantId = new Guid("20000000-0008-0000-0000-000000000001"),
                            IsActive = true,
                            UnitPrice = 540000m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0012-2000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999992"),
                            InStockProductVariantId = new Guid("20000000-0008-0000-0000-000000000001"),
                            IsActive = true,
                            UnitPrice = 432000.0m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0013-1000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999991"),
                            InStockProductVariantId = new Guid("20000000-0008-0000-0000-000000000002"),
                            IsActive = true,
                            UnitPrice = 330000m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0013-2000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999992"),
                            InStockProductVariantId = new Guid("20000000-0008-0000-0000-000000000002"),
                            IsActive = true,
                            UnitPrice = 264000.0m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0014-1000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999991"),
                            InStockProductVariantId = new Guid("20000000-0009-0000-0000-000000000001"),
                            IsActive = true,
                            UnitPrice = 42000m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0014-2000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999992"),
                            InStockProductVariantId = new Guid("20000000-0009-0000-0000-000000000001"),
                            IsActive = true,
                            UnitPrice = 33600.0m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0015-1000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999991"),
                            InStockProductVariantId = new Guid("20000000-0010-0000-0000-000000000001"),
                            IsActive = true,
                            UnitPrice = 867000m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0015-2000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999992"),
                            InStockProductVariantId = new Guid("20000000-0010-0000-0000-000000000001"),
                            IsActive = true,
                            UnitPrice = 693600.0m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0016-1000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999991"),
                            InStockProductVariantId = new Guid("20000000-0010-0000-0000-000000000002"),
                            IsActive = true,
                            UnitPrice = 509000m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("30000000-0016-2000-0000-000000000000"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockPriceId = new Guid("99999999-9999-9999-9999-999999999992"),
                            InStockProductVariantId = new Guid("20000000-0010-0000-0000-000000000002"),
                            IsActive = true,
                            UnitPrice = 407200.0m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PuzKit3D.Modules.Cart.Domain.Entities.Replicas.InStockProductReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssemblyMethodId")
                        .HasColumnType("uuid")
                        .HasColumnName("assembly_method_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DifficultLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficult_level");

                    b.Property<int>("EstimatedBuildTime")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_build_time");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<string>("PreviewAsset")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("preview_asset");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("slug");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<int>("TotalPieceCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_piece_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_in_stock_product_replicas");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UK__instock_product_replica__slug");

                    b.ToTable("in_stock_product_replicas", "cart");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            AssemblyMethodId = new Guid("d1d1d1d1-d1d1-d1d1-d1d1-d1d1d1d1d1d1"),
                            Code = "INP001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "New wooden mechanical 3D puzzle UGT-24 Endurance Racer by Ugears. A large car featuring a blue racing stripe and plastic windows drives 5-6 m thanks to a spring motor. Cool gift!",
                            DifficultLevel = "Basic",
                            EstimatedBuildTime = 120,
                            IsActive = true,
                            MaterialId = new Guid("f1f1f1f1-f1f1-f1f1-f1f1-f1f1f1f1f1f1"),
                            Name = "UGT-24 Endurance Racer",
                            PreviewAsset = "{\"additionalProp1\":\"instock-products/ugt-24-endurance-racer/image-01.png\",\"additionalProp2\":\"instock-products/ugt-24-endurance-racer/image-02.png\"}",
                            Slug = "ugt-24-endurance-racer",
                            ThumbnailUrl = "instock-products/ugt-24-endurance-racer/thumbnail.png",
                            TopicId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            TotalPieceCount = 150,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            AssemblyMethodId = new Guid("e2e2e2e2-e2e2-e2e2-e2e2-e2e2e2e2e2e2"),
                            Code = "INP002",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wooden 3D puzzle Mad Hornet Airplane from Ugears. Pre-flight check mode and taxi mode. Moves without batteries. Assemble without glue. The perfect gift!",
                            DifficultLevel = "Intermediate",
                            EstimatedBuildTime = 180,
                            IsActive = true,
                            MaterialId = new Guid("a2a2a2a2-a2a2-a2a2-a2a2-a2a2a2a2a2a2"),
                            Name = "Mad Hornet Airplane",
                            PreviewAsset = "{\"additionalProp1\":\"instock-products/mad-hornet-airplane/image-01.png\",\"additionalProp2\":\"instock-products/mad-hornet-airplane/image-02.png\"}",
                            Slug = "mad-hornet-airplane",
                            ThumbnailUrl = "instock-products/mad-hornet-airplane/thumbnail.png",
                            TopicId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            TotalPieceCount = 200,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            AssemblyMethodId = new Guid("f3f3f3f3-f3f3-f3f3-f3f3-f3f3f3f3f3f3"),
                            Code = "INP003",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "New wooden mechanical 3D puzzle UGT-24 Endurance Racer by Ugears. A large car featuring a blue racing stripe and plastic windows drives 5-6 m thanks to a spring motor. Cool gift!",
                            DifficultLevel = "Advanced",
                            EstimatedBuildTime = 240,
                            IsActive = true,
                            MaterialId = new Guid("b3b3b3b3-b3b3-b3b3-b3b3-b3b3b3b3b3b3"),
                            Name = "Eagle 3D Puzzle",
                            PreviewAsset = "{\"additionalProp1\":\"instock-products/ugt-24-endurance-racer/image-01.png\",\"additionalProp2\":\"instock-products/ugt-24-endurance-racer/image-02.png\"}",
                            Slug = "eagle-3d-puzzle",
                            ThumbnailUrl = "instock-products/ugt-24-endurance-racer/thumbnail.png",
                            TopicId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            TotalPieceCount = 180,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            AssemblyMethodId = new Guid("a4a4a4a4-a4a4-a4a4-a4a4-a4a4a4a4a4a4"),
                            Code = "INP004",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wooden 3D puzzle Mad Hornet Airplane from Ugears. Pre-flight check mode and taxi mode. Moves without batteries. Assemble without glue. The perfect gift!",
                            DifficultLevel = "Advanced",
                            EstimatedBuildTime = 300,
                            IsActive = true,
                            MaterialId = new Guid("c4c4c4c4-c4c4-c4c4-c4c4-c4c4c4c4c4c4"),
                            Name = "Sports Car 3D Puzzle",
                            PreviewAsset = "{\"additionalProp1\":\"instock-products/mad-hornet-airplane/image-01.png\",\"additionalProp2\":\"instock-products/mad-hornet-airplane/image-02.png\"}",
                            Slug = "sports-car-3d-puzzle",
                            ThumbnailUrl = "instock-products/mad-hornet-airplane/thumbnail.png",
                            TopicId = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            TotalPieceCount = 250,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            AssemblyMethodId = new Guid("b5b5b5b5-b5b5-b5b5-b5b5-b5b5b5b5b5b5"),
                            Code = "INP005",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "New wooden mechanical 3D puzzle UGT-24 Endurance Racer by Ugears. A large car featuring a blue racing stripe and plastic windows drives 5-6 m thanks to a spring motor. Cool gift!",
                            DifficultLevel = "Intermediate",
                            EstimatedBuildTime = 200,
                            IsActive = true,
                            MaterialId = new Guid("d5d5d5d5-d5d5-d5d5-d5d5-d5d5d5d5d5d5"),
                            Name = "Airplane 3D Puzzle",
                            PreviewAsset = "{\"additionalProp1\":\"instock-products/ugt-24-endurance-racer/image-01.png\",\"additionalProp2\":\"instock-products/ugt-24-endurance-racer/image-02.png\"}",
                            Slug = "airplane-3d-puzzle",
                            ThumbnailUrl = "instock-products/ugt-24-endurance-racer/thumbnail.png",
                            TopicId = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            TotalPieceCount = 220,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            AssemblyMethodId = new Guid("d1d1d1d1-d1d1-d1d1-d1d1-d1d1d1d1d1d1"),
                            Code = "INP006",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "New wooden mechanical 3D puzzle UGT-24 Endurance Racer by Ugears. A large car featuring a blue racing stripe and plastic windows drives 5-6 m thanks to a spring motor. Cool gift!",
                            DifficultLevel = "Intermediate",
                            EstimatedBuildTime = 150,
                            IsActive = true,
                            MaterialId = new Guid("f1f1f1f1-f1f1-f1f1-f1f1-f1f1f1f1f1f1"),
                            Name = "Motorcycle 3D Puzzle",
                            PreviewAsset = "{\"additionalProp1\":\"instock-products/ugt-24-endurance-racer/image-01.png\",\"additionalProp2\":\"instock-products/ugt-24-endurance-racer/image-02.png\"}",
                            Slug = "motorcycle-3d-puzzle",
                            ThumbnailUrl = "instock-products/ugt-24-endurance-racer/thumbnail.png",
                            TopicId = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            TotalPieceCount = 180,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            AssemblyMethodId = new Guid("e2e2e2e2-e2e2-e2e2-e2e2-e2e2e2e2e2e2"),
                            Code = "INP007",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wooden 3D puzzle Mad Hornet Airplane from Ugears. Pre-flight check mode and taxi mode. Moves without batteries. Assemble without glue. The perfect gift!",
                            DifficultLevel = "Basic",
                            EstimatedBuildTime = 130,
                            IsActive = true,
                            MaterialId = new Guid("a2a2a2a2-a2a2-a2a2-a2a2-a2a2a2a2a2a2"),
                            Name = "Tiger 3D Puzzle",
                            PreviewAsset = "{\"additionalProp1\":\"instock-products/mad-hornet-airplane/image-01.png\",\"additionalProp2\":\"instock-products/mad-hornet-airplane/image-02.png\"}",
                            Slug = "tiger-3d-puzzle",
                            ThumbnailUrl = "instock-products/mad-hornet-airplane/thumbnail.png",
                            TopicId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            TotalPieceCount = 170,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            AssemblyMethodId = new Guid("f3f3f3f3-f3f3-f3f3-f3f3-f3f3f3f3f3f3"),
                            Code = "INP008",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wooden 3D puzzle Mad Hornet Airplane from Ugears. Pre-flight check mode and taxi mode. Moves without batteries. Assemble without glue. The perfect gift!",
                            DifficultLevel = "Basic",
                            EstimatedBuildTime = 100,
                            IsActive = true,
                            MaterialId = new Guid("b3b3b3b3-b3b3-b3b3-b3b3-b3b3b3b3b3b3"),
                            Name = "Dolphin 3D Puzzle",
                            PreviewAsset = "{\"additionalProp1\":\"instock-products/mad-hornet-airplane/image-01.png\",\"additionalProp2\":\"instock-products/mad-hornet-airplane/image-02.png\"}",
                            Slug = "dolphin-3d-puzzle",
                            ThumbnailUrl = "instock-products/mad-hornet-airplane/thumbnail.png",
                            TopicId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            TotalPieceCount = 130,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            AssemblyMethodId = new Guid("e2e2e2e2-e2e2-e2e2-e2e2-e2e2e2e2e2e2"),
                            Code = "INP009",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "New wooden mechanical 3D puzzle UGT-24 Endurance Racer by Ugears. A large car featuring a blue racing stripe and plastic windows drives 5-6 m thanks to a spring motor. Cool gift!",
                            DifficultLevel = "Intermediate",
                            EstimatedBuildTime = 170,
                            IsActive = true,
                            MaterialId = new Guid("a2a2a2a2-a2a2-a2a2-a2a2-a2a2a2a2a2a2"),
                            Name = "Helicopter 3D Puzzle",
                            PreviewAsset = "{\"additionalProp1\":\"instock-products/ugt-24-endurance-racer/image-01.png\",\"additionalProp2\":\"instock-products/ugt-24-endurance-racer/image-02.png\"}",
                            Slug = "helicopter-3d-puzzle",
                            ThumbnailUrl = "instock-products/ugt-24-endurance-racer/thumbnail.png",
                            TopicId = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            TotalPieceCount = 190,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            AssemblyMethodId = new Guid("a4a4a4a4-a4a4-a4a4-a4a4-a4a4a4a4a4a4"),
                            Code = "INP010",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wooden 3D puzzle Mad Hornet Airplane from Ugears. Pre-flight check mode and taxi mode. Moves without batteries. Assemble without glue. The perfect gift!",
                            DifficultLevel = "Advanced",
                            EstimatedBuildTime = 360,
                            IsActive = true,
                            MaterialId = new Guid("c4c4c4c4-c4c4-c4c4-c4c4-c4c4c4c4c4c4"),
                            Name = "Dragon 3D Puzzle",
                            PreviewAsset = "{\"additionalProp1\":\"instock-products/mad-hornet-airplane/image-01.png\",\"additionalProp2\":\"instock-products/mad-hornet-airplane/image-02.png\"}",
                            Slug = "dragon-3d-puzzle",
                            ThumbnailUrl = "instock-products/mad-hornet-airplane/thumbnail.png",
                            TopicId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            TotalPieceCount = 300,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PuzKit3D.Modules.Cart.Domain.Entities.Replicas.InStockProductVariantReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AssembledHeightMm")
                        .HasColumnType("integer")
                        .HasColumnName("assembled_height_mm");

                    b.Property<int>("AssembledLengthMm")
                        .HasColumnType("integer")
                        .HasColumnName("assembled_length_mm");

                    b.Property<int>("AssembledWidthMm")
                        .HasColumnType("integer")
                        .HasColumnName("assembled_width_mm");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InStockProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("in_stock_product_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sku");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_in_stock_product_variant_replicas");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("UK__instock_product_variant_replica__sku");

                    b.ToTable("in_stock_product_variant_replicas", "cart");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0001-0000-0000-000000000001"),
                            AssembledHeightMm = 261,
                            AssembledLengthMm = 218,
                            AssembledWidthMm = 159,
                            Color = "Red",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Sku = "SKU001",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0001-0000-0000-000000000002"),
                            AssembledHeightMm = 297,
                            AssembledLengthMm = 174,
                            AssembledWidthMm = 138,
                            Color = "Blue",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Sku = "SKU002",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0002-0000-0000-000000000001"),
                            AssembledHeightMm = 175,
                            AssembledLengthMm = 229,
                            AssembledWidthMm = 263,
                            Color = "Green",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Sku = "SKU003",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0003-0000-0000-000000000001"),
                            AssembledHeightMm = 224,
                            AssembledLengthMm = 131,
                            AssembledWidthMm = 171,
                            Color = "Yellow",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Sku = "SKU004",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0003-0000-0000-000000000002"),
                            AssembledHeightMm = 289,
                            AssembledLengthMm = 182,
                            AssembledWidthMm = 292,
                            Color = "Black",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Sku = "SKU005",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0004-0000-0000-000000000001"),
                            AssembledHeightMm = 158,
                            AssembledLengthMm = 156,
                            AssembledWidthMm = 240,
                            Color = "White",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Sku = "SKU006",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0004-0000-0000-000000000002"),
                            AssembledHeightMm = 127,
                            AssembledLengthMm = 225,
                            AssembledWidthMm = 187,
                            Color = "Orange",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Sku = "SKU007",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0005-0000-0000-000000000001"),
                            AssembledHeightMm = 222,
                            AssembledLengthMm = 219,
                            AssembledWidthMm = 201,
                            Color = "Purple",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Sku = "SKU008",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0006-0000-0000-000000000001"),
                            AssembledHeightMm = 227,
                            AssembledLengthMm = 154,
                            AssembledWidthMm = 278,
                            Color = "Red",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Sku = "SKU009",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0006-0000-0000-000000000002"),
                            AssembledHeightMm = 152,
                            AssembledLengthMm = 288,
                            AssembledWidthMm = 296,
                            Color = "Blue",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Sku = "SKU010",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0007-0000-0000-000000000001"),
                            AssembledHeightMm = 177,
                            AssembledLengthMm = 221,
                            AssembledWidthMm = 207,
                            Color = "Green",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductId = new Guid("10000000-0000-0000-0000-000000000007"),
                            IsActive = true,
                            Sku = "SKU011",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0008-0000-0000-000000000001"),
                            AssembledHeightMm = 297,
                            AssembledLengthMm = 137,
                            AssembledWidthMm = 135,
                            Color = "Yellow",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Sku = "SKU012",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0008-0000-0000-000000000002"),
                            AssembledHeightMm = 274,
                            AssembledLengthMm = 195,
                            AssembledWidthMm = 221,
                            Color = "Black",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Sku = "SKU013",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0009-0000-0000-000000000001"),
                            AssembledHeightMm = 102,
                            AssembledLengthMm = 146,
                            AssembledWidthMm = 111,
                            Color = "White",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductId = new Guid("10000000-0000-0000-0000-000000000009"),
                            IsActive = true,
                            Sku = "SKU014",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0010-0000-0000-000000000001"),
                            AssembledHeightMm = 154,
                            AssembledLengthMm = 265,
                            AssembledWidthMm = 262,
                            Color = "Orange",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Sku = "SKU015",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0010-0000-0000-000000000002"),
                            AssembledHeightMm = 251,
                            AssembledLengthMm = 150,
                            AssembledWidthMm = 186,
                            Color = "Purple",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InStockProductId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Sku = "SKU016",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PuzKit3D.Modules.Cart.Domain.Entities.Replicas.PartnerProductReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BriefDescription")
                        .HasColumnType("text")
                        .HasColumnName("brief_description");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetailDescription")
                        .HasColumnType("text")
                        .HasColumnName("detail_description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<string>("PartnerProductSku")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("partner_product_sku");

                    b.Property<string>("PreviewAsset")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("preview_asset");

                    b.Property<string>("ProductCatalog")
                        .HasColumnType("jsonb")
                        .HasColumnName("product_catalog");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("slug");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_partner_product_replicas");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UK__partner_product_replica__slug");

                    b.HasIndex("PartnerId", "PartnerProductSku")
                        .IsUnique()
                        .HasDatabaseName("CUK___partner_product_replica___partner_id__partner_product_sku");

                    b.ToTable("partner_product_replicas", "cart");
                });

            modelBuilder.Entity("PuzKit3D.Modules.Cart.Domain.Entities.Replicas.UserReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("address");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_user_replicas");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UK__user_replica__email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("UK__user_replica__phone_number");

                    b.ToTable("user_replicas", "cart");
                });

            modelBuilder.Entity("PuzKit3D.Modules.Cart.Domain.Entities.Carts.CartItem", b =>
                {
                    b.HasOne("PuzKit3D.Modules.Cart.Domain.Entities.Carts.Cart", null)
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__cart__cart_item");
                });

            modelBuilder.Entity("PuzKit3D.Modules.Cart.Domain.Entities.Carts.Cart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
