// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PuzKit3D.Modules.SupportTicket.Persistence;

#nullable disable

namespace PuzKit3D.Modules.SupportTicket.Persistence.Migrations
{
    [DbContext(typeof(SupportTicketDbContext))]
    partial class SupportTicketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PuzKit3D.Modules.SupportTicket.Domain.Entities.CompletedOrderItemReplicas.CompletedOrderItemReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompletedOrderReplicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_order_replica_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.HasKey("Id")
                        .HasName("pk_completed_order_item_replicas");

                    b.HasIndex("CompletedOrderReplicaId")
                        .HasDatabaseName("ix_completed_order_item_replicas_completed_order_replica_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_completed_order_item_replicas_product_id");

                    b.ToTable("completed_order_item_replicas", (string)null);
                });

            modelBuilder.Entity("PuzKit3D.Modules.SupportTicket.Domain.Entities.CompletedOrderReplicas.CompletedOrderReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_completed_order_replicas");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_completed_order_replicas_customer_id");

                    b.ToTable("completed_order_replicas", (string)null);
                });

            modelBuilder.Entity("PuzKit3D.Modules.SupportTicket.Domain.Entities.SupportTicketDetails.SupportTicketDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_id");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid")
                        .HasColumnName("part_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SupportTicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("support_ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_support_ticket_details");

                    b.HasIndex("PartId")
                        .HasDatabaseName("ix_support_ticket_details_part_id");

                    b.HasIndex("SupportTicketId")
                        .HasDatabaseName("ix_support_ticket_details_support_ticket_id");

                    b.ToTable("support_ticket_details", (string)null);
                });

            modelBuilder.Entity("PuzKit3D.Modules.SupportTicket.Domain.Entities.SupportTickets.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Proof")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("proof");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_support_tickets");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_support_tickets_order_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_support_tickets_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_support_tickets_user_id");

                    b.ToTable("support_tickets", (string)null);
                });

            modelBuilder.Entity("PuzKit3D.Modules.SupportTicket.Domain.Entities.CompletedOrderItemReplicas.CompletedOrderItemReplica", b =>
                {
                    b.HasOne("PuzKit3D.Modules.SupportTicket.Domain.Entities.CompletedOrderReplicas.CompletedOrderReplica", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("CompletedOrderReplicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_completed_order_item_replicas_completed_order_replicas_comp");
                });

            modelBuilder.Entity("PuzKit3D.Modules.SupportTicket.Domain.Entities.SupportTicketDetails.SupportTicketDetail", b =>
                {
                    b.HasOne("PuzKit3D.Modules.SupportTicket.Domain.Entities.SupportTickets.SupportTicket", null)
                        .WithMany("Details")
                        .HasForeignKey("SupportTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_support_ticket_details_support_tickets_support_ticket_id");
                });

            modelBuilder.Entity("PuzKit3D.Modules.SupportTicket.Domain.Entities.CompletedOrderReplicas.CompletedOrderReplica", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("PuzKit3D.Modules.SupportTicket.Domain.Entities.SupportTickets.SupportTicket", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
