// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PuzKit3D.Modules.Wallet.Persistence;

#nullable disable

namespace PuzKit3D.Modules.Wallet.Persistence.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    [Migration("20260330024233_InitModule")]
    partial class InitModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("wallet")
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PuzKit3D.Modules.Wallet.Domain.Entities.WalletConfigs.WalletConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CODOrderCompletedRewardPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("cod_order_completed_reward_percentage");

                    b.Property<decimal>("OnlineOrderCompletedRewardPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("online_order_completed_reward_percentage");

                    b.Property<decimal>("OnlineOrderReturnPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("online_order_return_percentage");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_wallet_configs");

                    b.ToTable("wallet_configs", "wallet");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CODOrderCompletedRewardPercentage = 2m,
                            OnlineOrderCompletedRewardPercentage = 5m,
                            OnlineOrderReturnPercentage = 80m,
                            UpdatedAt = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PuzKit3D.Modules.Wallet.Domain.Entities.WalletTransactions.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_wallet_transactions");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_wallet_transactions_order_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_wallet_transactions_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_wallet_transactions_user_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_wallet_transactions_user_id_created_at");

                    b.ToTable("wallet_transactions", "wallet");
                });

            modelBuilder.Entity("PuzKit3D.Modules.Wallet.Domain.Entities.Wallets.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_wallets");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_wallets_user_id");

                    b.ToTable("wallets", "wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
